[tool.poetry]
name = "shopproject"
version = "0.1.0"
description = "Payment Reminder Tool"
authors = ["ManjunathArroaa <manjunathtmanju080@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.109.0"
uvicorn = {extras = ["standard"], version = "0.27.0"}
sqlalchemy = "2.0.25"
pydantic = "2.10.3"
python-dotenv = "1.0.0"
pydantic-settings = "2.5.0"
python-multipart = "0.0.6"
passlib = "1.7.4"
bcrypt = "4.0.1"
python-jose = {extras = ["cryptography"], version = "3.3.0"}
apscheduler = "3.10.4"
requests = "2.31.0"
python-dateutil = "2.8.2"
twilio = "8.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"